[workspace]
resolver = "2"
members = [
    "fancy-garbling",
    "humidor",
    "keyed_arena",
    "ocelot",
    "popsicle",
    "scuttlebutt",
    "simple-arith-circuit",
    "vectoreyes",
]

[profile.release]
opt-level = 3
debug = true
lto = true
debug-assertions = false
overflow-checks = false
codegen-units = 1

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = true
lto = true
debug-assertions = false
overflow-checks = false

[profile.test]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
