version: '3'

services:
  verifier:
    image: swanky:latest
    volumes:
      #- ./scuttlebutt:/root/swanky/scuttlebutt
      - ./ocelot:/root/swanky/ocelot
    cap_add:
     - NET_ADMIN
    expose:
      - "5527"
    environment:
      - VERIFIER="True"
    command: bash -c "tail -f /dev/null" #bash test_edabits.sh
      # - "bash -c \"tail -f /dev/null\"" 

  prover:
    image: swanky:latest
    volumes:
      #- ./scuttlebutt:/root/swanky/scuttlebutt
      - ./ocelot:/root/swanky/ocelot
    environment:
      - PROVER="True"
    cap_add:
      - NET_ADMIN
    command: bash -c "tail -f /dev/null" #"bash test_edabits.sh"
    #- "bash -c \"tail -f /dev/null\""
