[package]
name = "humidor"
version = "0.0.1"
authors = ["Ben Hamlin <hamlinb@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A test-bed for Ligero-like protocols"
categories = ["cryptography"]
keywords = ["cryptography", "zero-knowledge-proofs", "ligero"]
edition = "2018"
autobenches = false
publish = false

[lib]
doctest = false

[features]

[dependencies]
merkle-cbt = "0.3.0"
rust-crypto = "^0.2.36"
tiny-keccak = { version = "2.0.0", features = ["sha3", "k12"] }
sprs = "0.9.3"
ndarray = "0.13.1"
num-traits = "0.2.14"
rand = "0.8.3"
static_assertions = "0.2.3"

[dependencies.threshold-secret-sharing]
git = "https://gitlab-ext.galois.com/hamlinb/rust-threshold-secret-sharing"
branch = "dev"

[dev-dependencies]
proptest = "0.10.1"
criterion = "0.3"

[[bench]]
name = "random_circuit"
harness = false

[[example]]
name = "random_circuit_interactive"

[[example]]
name = "random_circuit_noninteractive"
