[package]
name = "popsicle"
version = "0.4.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for private set intersection"
categories = ["cryptography"]
keywords = ["cryptography", "private-set-intersection", "PSI"]
edition = "2018"
publish = false

[lib]

[features]
nightly = ["scuttlebutt/nightly", "ocelot/nightly", "ocelot/nightly"]
psty = ["fancy-garbling", "openssl"]

[dependencies]
ocelot         = { path = "../ocelot" }
scuttlebutt    = { path = "../scuttlebutt" }
itertools      = "0.10.0"
rand           = "0.7"
sha2           = "0.9.3"
fancy-garbling = { path = "../fancy-garbling", optional = true }
openssl        = { version = "0.10.32", optional = true }

[dev-dependencies]
criterion  = "0.3.4"
clap       = "2.33.3"
serde      = { version = "1.0.123", features = ["derive"] }
serde_yaml = "0.8.17"
rustyline  = "7.1.0"
pbr        = "1.0.4"
ascii      = "1.0.0"

[[bench]]
name = "psz"
harness = false

[[bench]]
name = "psty"
harness = false
required-features = ["psty"]

[[example]]
name = "psty"
required-features = ["psty"]

[[example]]
name = "psty-payload"
required-features = ["psty"]

[[example]]
name = "secretsister"
required-features = ["psty"]
