[package]
name = "ocelot"
version = "0.4.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for oblivious transfer protocols"
categories = ["cryptography"]
keywords = ["cryptography", "oblivious-transfer", "OT"]
edition = "2018"
publish = false
build = "build.rs"
autoexamples = true

[lib]

[features]
nightly = ["curve25519-dalek/nightly", "curve25519-dalek/simd_backend", "scuttlebutt/nightly"]


[dependencies]
blake3 = "0.3.7"
curve25519-dalek = { version = "3.0.2", features = ["std"] }
rand = "0.7"
scuttlebutt = { path = "../scuttlebutt", features = ["curve25519-dalek"] }
vectoreyes = { path = "../vectoreyes" }
generic-array = "0.14.4"
subtle = "2.4.0"

[build-dependencies]
cc = "1.0.67"

[dev-dependencies]
criterion = "0.3.4"
nix = "0.20.0"

[[bench]]
name = "ot"
harness = false

[[bench]]
name = "oprf"
harness = false

[[bench]]
name = "svole"
harness = false

[[example]]
name = "kmprt"
harness = false
