[package]
name = "ocelot"
version = "0.4.0"
authors = ["swanky authors <swanky@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for oblivious transfer protocols"
categories = ["cryptography"]
keywords = ["cryptography", "oblivious-transfer", "OT"]
edition = "2021"
publish = false
build = "build.rs"
autoexamples = true

[lib]

[features]
nightly = ["curve25519-dalek/nightly", "curve25519-dalek/simd_backend", "scuttlebutt/nightly"]


[dependencies]
blake3 = "1.3.1"
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4" }
rand = "0.8.5"
scuttlebutt = { path = "../scuttlebutt", features = ["curve25519-dalek"] }
vectoreyes = { path = "../vectoreyes" }
generic-array = "0.14.5"
subtle = "2.4.1"
bytemuck = "1.8.0"

[build-dependencies]
cc = "1.0.73"

[dev-dependencies]
criterion = "0.3.5"
nix = "0.23.1"
proptest = "1.0.0"
clap = "2.33.3"
tikv-jemallocator = "0.4.3"

[[bench]]
name = "ot"
harness = false

[[bench]]
name = "oprf"
harness = false

[[bench]]
name = "svole"
harness = false

[[example]]
name = "kmprt"
harness = false
