[package]
name = "ocelot"
version = "0.4.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for oblivious transfer protocols"
categories = ["cryptography"]
keywords = ["cryptography", "oblivious-transfer", "OT"]
edition = "2018"
publish = false
build = "build.rs"
autoexamples = true

[lib]

[features]
nightly = ["curve25519-dalek/avx2_backend", "rand/nightly", "scuttlebutt/nightly"]

[dependencies]
curve25519-dalek = { version = "2", features = ["std"] }
rand = "0.7"
rand_core = "0.5"
scuttlebutt = { path = "../scuttlebutt", features = ["curve25519-dalek"] }
generic-array = "0.14"
subtle = "2.2"


[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = "0.2"


[[bench]]
name = "ot"
harness = false

[[bench]]
name = "oprf"
harness = false

[[bench]]
path = "benches/base_svole.rs"
name = "base_svole"
harness = false

[[example]]
name = "kmprt"
harness = false
