[package]
name = "scuttlebutt"
version = "0.4.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library of useful multi-party computation utilities"
keywords = ["cryptography", "MPC", "secure-computation"]
categories = ["cryptography"]
edition = "2018"
publish = false

[features]
nightly = ["curve25519-dalek/nightly", "curve25519-dalek/simd_backend"]
unstable = []
serde1 = []

[dependencies]
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", optional = true }
rand = "0.8.5"
rand_core = "0.6.3"
serde = { version = "1.0.136", features = ["derive"] }
sha2 = "0.10.2"
subtle = "2.4.1"
primitive-types = "0.11.1"
uint = "0.9.3"
generic-array = "0.14.5"
smallvec = "1.8.0"
bytemuck = { version = "1.8.0", features = ["derive"] }
vectoreyes = { path = "../vectoreyes" }
ndarray = "0.15.4"
num-traits = "0.2.14"


[dev-dependencies]
criterion = "0.3.5"
hex = "0.4.3"
proptest = "1.0.0"
num-bigint = "0.4.3"

[target.'cfg(target_os="linux")'.dev-dependencies]
criterion-linux-perf = "0.1.0"

[[bench]]
name = "aes128"
harness = false

[[bench]]
name = "aes256"
harness = false

[[bench]]
name = "block"
harness = false

[[bench]]
name = "block512"
harness = false

[[bench]]
name = "commitment"
harness = false

[[bench]]
name = "hash_aes"
harness = false

[[bench]]
name = "rand_aes"
harness = false

[[bench]]
name = "prime_field"
harness = false

[[bench]]
name = "gf_2_128"
harness = false

[[bench]]
name = "f61p"
harness = false

[[bench]]
name = "gf_2_45"
harness = false

[[bench]]
name = "gf_2_40"
harness = false

[[bench]]
name = "f2_19x3_26"
harness = false
