[package]
name = "scuttlebutt"
version = "0.4.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library of useful multi-party computation utilities"
keywords = ["cryptography", "MPC", "secure-computation"]
categories = ["cryptography"]
edition = "2018"
publish = false

[lib]

[features]
nightly = ["curve25519-dalek/avx2_backend", "rand/nightly"]
unstable = []
serde1 = ["serde"]

[dependencies]
curve25519-dalek = { version = "2", features = ["std"], optional = true }
rand = "0.7"
rand_core = "0.5"
serde = { version = "1", features = ["derive"], optional = true }
sha2 = "0.8"
subtle = "2.2"
primitive-types = "0.7"
uint = "0.8"
generic-array = "0.14"
digest = "0.9.0"

[dev-dependencies]
criterion = "0.2"
hex = "0.3"
quickcheck = "0.9"
quickcheck_macros = "0.9"
num-bigint = "0.3"

[[bench]]
name = "aes128"
harness = false

[[bench]]
name = "aes256"
harness = false

[[bench]]
name = "block"
harness = false

[[bench]]
name = "block512"
harness = false

[[bench]]
name = "commitment"
harness = false

[[bench]]
name = "hash_aes"
harness = false

[[bench]]
name = "rand_aes"
harness = false

[[bench]]
name = "prime_field"
harness = false

[[bench]]
name = "gf_2_128"
harness = false

